AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Send all S3 PutBucketTagging events to a custom event bus in the organisation account


Parameters:

  OrganizationAccountNumber:
    Type: String
    Description: The Org account number
    Default: "111111111111"

  CustomEventBusName:
    Type: String
    Description: The name of the custom event bus
    Default: SOAR-events


Resources:

  S3PutBucketTaggingRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: Send all S3 PutBucketTagging events to the custom event bus SOAR-events in the organisation account
      State: ENABLED
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource: 
            - s3.amazonaws.com
          eventName: 
            - PutBucketTagging
      Targets:
        - Id: S3TaggingToOrgAccount
          Arn: !Sub "arn:aws:events:${AWS::Region}:${OrganizationAccountNumber}:event-bus/${CustomEventBusName}"
          RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/EventBridgeInvokeEventBusRole"
